[target.x86_64-unknown-linux-gnu]
rustflags = [
    # Configuración simplificada para evitar errores de ABI
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "opt-level=z",
    "-C", "inline-threshold=275",
]
